repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff          # linter
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format   # formatter
        stages: [pre-commit]
