name: Benchmark CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, converted_to_draft, ready_for_review, synchronize]
    branches: [master]

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize CI
        run: echo "CI initialized"