name: Temporary MATLAB Setup

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-matlab:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run temporary setup script
        uses: matlab-actions/run-command@v2
        with:
            command: addpath("setup"), test_matlab
