name: Temporary MATLAB Setup

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-matlab:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run temporary setup script
        uses: matlab-actions/run-command@v2
        with:
            command: addpath("setup"), test_matlab
        
      - name: Install QETLAB and CVX
        run: |
            wget https://github.com/nathanieljohnston/QETLAB/archive/v0.9.zip -O QETLAB.zip
            unzip QETLAB.zip -d QETLAB
        
      - name: Run QETLAB benchmark suite
        uses: matlab-actions/run-command@v2
        with:
          command: |
            run("abc.m")
            

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: PartialTraceBenchmarks_results
          path: PartialTraceBenchmarks_results.csv

            
            
